-- V4__seed_designs.sql
-- Seeds 10 real design records into the designs table (migrated from design-studio.js mock data)
-- Tags, swatches, and image_urls are stored as comma-separated TEXT

INSERT INTO designs (
    id, design_code, title, garment_type, status, designer, thumbnail_url,
    sub_category, style, occasion, collection, primary_fabric,
    colour_options, sizes, construction, embroidery,
    estimated_cost, suggested_price, estimated_labour,
    production_status, times_used, last_used_date,
    tags, swatches, image_urls, notes, created_by,
    created_at, updated_at
) VALUES

-- 1. Zari Bloom
(
    gen_random_uuid(),
    'DS-2026-001',
    'Zari Bloom',
    'Blouse',
    'APPROVED',
    'Priya S',
    '../assets/designs/zari-bloom-front.jpg',
    'Bridal Couture',
    'Embroidered',
    'Wedding',
    'Royal Heritage',
    'Banarasi Raw Silk',
    'Crimson Red, Emerald Green, Royal Blue, Mustard Gold',
    'Custom / Made to Measure',
    'Padded, Sweetheart Neck, Dori Tie Back',
    'Antique Zari, Cutdana Beads, Micro Sequins',
    2850.00, 8500.00, '6 hours',
    'Active', 18, '2026-09-06',
    'Bridal,Zari,Handwork,Bestseller,Sweetheart Neck',
    '#B82E5A,#D4AF37,#2D5A27',
    '../assets/designs/zari-bloom-front.jpg,../assets/designs/zari-bloom-back.jpg,../assets/designs/zari-bloom-detail.jpg',
    'Intricate floral zari jaal with sweetheart neckline and tasseled dori tie back.',
    'Priya S',
    now(), now()
),

-- 2. Garden Party Lehenga
(
    gen_random_uuid(),
    'DS-2026-002',
    'Garden Party Lehenga',
    'Lehenga',
    'APPROVED',
    'Aditi Rao',
    '../assets/designs/garden-party.jpg',
    'Mehendi & Sangeet',
    'Printed & Embroidered',
    'Sangeet',
    'Spring Blossom',
    'Organza Silk',
    'Blush Pink, Mint Green, Lilac, Champagne',
    'Custom Waist & Length',
    'Can-Can Layered, Cancan Net, Side Zip with Tassels',
    'Resham Threadwork, Pearl Beads & Mirrors',
    7200.00, 24000.00, '16 hours',
    'Active', 12, '2026-09-09',
    'Pastel,Floral,Organza,Flared Skirt',
    '#E6A7B8,#F7D070,#A9E8D8',
    '../assets/designs/garden-party.jpg,../assets/designs/lehenga-mannequin.png',
    'Lightweight 24-kali organza skirt with hand-embroidered pearl blouse and sheer dupatta.',
    'Aditi Rao',
    now(), now()
),

-- 3. Regal Drape Saree
(
    gen_random_uuid(),
    'DS-2026-003',
    'Regal Drape Saree',
    'Saree',
    'APPROVED',
    'Priya S',
    '../assets/designs/regal-drape.jpg',
    'Heritage Weaves',
    'Woven Brocade',
    'Wedding',
    'Varanasi Gold',
    'Kanjivaram Pure Silk',
    'Vermilion Red, Peacock Blue, Mustard Korvai',
    'Standard 6.2m with Blouse Piece',
    'Traditional Korvai Weave, Heavy Pallu with Tassels',
    'Authentic Zari Weaving on Loom',
    11500.00, 32000.00, '4 hours (Tailoring & Fall Pico)',
    'Active', 15, '2026-09-08',
    'Heritage,Silk Mark,Gold Zari,Bridal',
    '#991B1B,#D97706,#4338CA',
    '../assets/designs/regal-drape.jpg,../assets/designs/saree-stage.png',
    'Pure mulberry silk with real gold-coated zari pallu and matching contrast blouse.',
    'Priya S',
    now(), now()
),

-- 4. Midnight Grace Gown
(
    gen_random_uuid(),
    'DS-2026-004',
    'Midnight Grace Gown',
    'Gown',
    'APPROVED',
    'Aditi Rao',
    '../assets/designs/midnight-grace.jpg',
    'Evening Soiree',
    'Contemporary Silhouette',
    'Reception',
    'Nocturne Elegance',
    'Micro Velvet & Satin',
    'Midnight Blue, Wine Bordeaux, Obsidian Black',
    'Custom Fitted',
    'Boning Corset Bodice, Off-Shoulder, Thigh-high Draped Slit',
    'Bugle Beads, Jet Black Crystals along Corset',
    6500.00, 19500.00, '12 hours',
    'Active', 8, '2026-09-01',
    'Evening Wear,Velvet,Corset,Slit Gown',
    '#1E1B4B,#312E81,#0F172A',
    '../assets/designs/midnight-grace.jpg,../assets/designs/gown-mannequin.png',
    'Architectural structured corset gown crafted in plush velvet with a flared satin train.',
    'Aditi Rao',
    now(), now()
),

-- 5. Meadow Grace Kurti
(
    gen_random_uuid(),
    'DS-2026-005',
    'Meadow Grace Kurti',
    'Kurti',
    'APPROVED',
    'Priya S',
    '../assets/designs/meadow-grace.jpg',
    'Luxury Pret',
    'A-Line Anarkali',
    'Festive',
    'Spring Blossom',
    'Chanderi Silk & Mulmul',
    'Sage Mint, Marigold Yellow, Dusty Rose',
    'S, M, L, XL, Custom',
    'Angrakha Style Yoke, 16 Kali Flare, Pockets',
    'Fine Gota Patti, Zardozi Floral Sprigs',
    2200.00, 6800.00, '5 hours',
    'Active', 22, '2026-09-07',
    'Chanderi,Anarkali,Pastel Green,Hand Embroidery',
    '#10B981,#F59E0B,#EC4899',
    '../assets/designs/meadow-grace.jpg,../assets/designs/kurti-mannequin.png',
    'Flowy Chanderi Anarkali kurti paired with cropped cigarette pants and organza dupatta.',
    'Priya S',
    now(), now()
),

-- 6. Classic Elegance Blouse
(
    gen_random_uuid(),
    'DS-2026-006',
    'Classic Elegance Blouse',
    'Blouse',
    'APPROVED',
    'Aditi Rao',
    '../assets/designs/classic-elegance.jpg',
    'Festive Occasion',
    'Gota Patti Work',
    'Festive',
    'Royal Heritage',
    'Tussar Silk with Gota Patti',
    'Mustard Gold, Rani Pink, Bottle Green',
    'Custom Made to Measure',
    'Princess Cut, Deep U-Back with Fabric Tie',
    'Rajasthani Gota Patti & Zari Borders',
    2400.00, 7200.00, '5.5 hours',
    'Active', 14, '2026-09-05',
    'Tussar,Gota Patti,Elbow Sleeve,Festive',
    '#D4AF37,#991B1B,#1E3A8A',
    '../assets/designs/classic-elegance.jpg,../assets/designs/blouse-stage.png',
    'Princess-cut Tussar blouse with Rajasthani gold gota patti border and elbow sleeves.',
    'Aditi Rao',
    now(), now()
),

-- 7. Indigo Dreams Suit
(
    gen_random_uuid(),
    'DS-2026-007',
    'Indigo Dreams Suit',
    'Suit',
    'IN_REVIEW',
    'Priya S',
    '../assets/designs/indigo-dreams.jpg',
    'Formal Pret',
    'Straight Cut',
    'Formal',
    'Everyday Luxury',
    'Handloom Cotton & Khadi',
    'Indigo Blue, Off-White, Slate Grey',
    'XS, S, M, L, XL, Custom',
    'Straight Cut Kurta, Cigarette Pant, Organza Dupatta',
    'Hand Block Print, Indigo Natural Dye',
    1900.00, 5700.00, '4 hours',
    'Active', 19, '2026-09-04',
    'Indigo,Block Print,Straight Cut,Summer',
    '#1E3A8A,#7C3AED,#1F2937',
    '../assets/designs/indigo-dreams.jpg,../assets/designs/suit-stage.png',
    'Hand block-printed indigo Khadi suit with matching cigarette pants and organza dupatta.',
    'Priya S',
    now(), now()
),

-- 8. Rose Ombre Sharara
(
    gen_random_uuid(),
    'DS-2026-008',
    'Rose Ombre Sharara',
    'Sharara',
    'APPROVED',
    'Aditi Rao',
    '../assets/designs/rose-ombre.jpg',
    'Festive Ethnic',
    'Ombre Printed',
    'Festive',
    'Spring Blossom',
    'Georgette & Net',
    'Blush to Magenta, Ivory to Gold, Lavender to Purple',
    'S, M, L, Custom',
    'Wide Leg Sharara, Flared Hem, Fringe Trim',
    'Sequin Border, Mukaish Work on Kurti',
    3200.00, 9600.00, '7 hours',
    'Active', 9, '2026-09-03',
    'Sharara,Ombre,Sequin,Festive',
    '#FB7185,#F9A8D4,#C084FC',
    '../assets/designs/rose-ombre.jpg,../assets/designs/sharara-stage.png',
    'Ombre dip-dyed georgette sharara with mukaish kurti and sheer net dupatta with sequin border.',
    'Aditi Rao',
    now(), now()
),

-- 9. Skyline Couture Gown
(
    gen_random_uuid(),
    'DS-2026-009',
    'Skyline Couture Gown',
    'Gown',
    'DRAFT',
    'Priya S',
    '../assets/designs/skyline.jpg',
    'Cocktail',
    'Mermaid Silhouette',
    'Party',
    'Modern Met Gala',
    'Duchess Satin & Net',
    'Ice Blue, Silver Lilac, Royal Sapphire',
    'Custom Fitted',
    'Sculpted Sweetheart Neckline with Flared Flounce',
    'Crystal Net Yoke & Sequined Accents',
    5800.00, 17500.00, '10 hours',
    'Active', 11, '2026-09-05',
    'Mermaid,Satin,Sculpted,Cocktail',
    '#60A5FA,#818CF8,#C084FC',
    '../assets/designs/skyline.jpg,../assets/designs/gown-stage.png',
    'Figure-contouring mermaid cocktail gown with structured shoulder flounce and crystal yoke.',
    'Priya S',
    now(), now()
),

-- 10. Minimal Muse Blouse
(
    gen_random_uuid(),
    'DS-2026-010',
    'Minimal Muse Blouse',
    'Blouse',
    'APPROVED',
    'Aditi Rao',
    '../assets/designs/minimal-muse.jpg',
    'Contemporary Classic',
    'Boat Neck Minimalist',
    'Formal',
    'Everyday Luxury',
    'Matka Silk with Threadwork',
    'Ivory White, Charcoal Grey, Tan Gold',
    'Custom Made to Measure',
    'Boat Neck, Elbow Sleeves, Concealed Side Zipper',
    'Tonal Hand Kantha Stitching along Neckline',
    1600.00, 4800.00, '3.5 hours',
    'Active', 31, '2026-09-09',
    'Boat Neck,Matka Silk,Minimalist,Workwear',
    '#1F2937,#4B5563,#F3F4F6',
    '../assets/designs/minimal-muse.jpg,../assets/designs/blouse-stage.png',
    'Sophisticated minimalist blouse suitable for handloom sarees and formal occasions.',
    'Aditi Rao',
    now(), now()
);
